version: '2.3'
services:
  matrix-ngx:
    container_name: matrix-ngx
    image: snowinmars/matrix-ngx:1.0.0
    # restart: unless-stopped
    build:
      context: ./ngx
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./ngx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ngx/https.conf:/etc/nginx/https.conf
      - ./ngx/cors.conf:/etc/nginx/cors.conf
      - ./ngx/acme-challenge:/var/www/html/acme-challenge
      - ./crt/letsencrypt:/etc/letsencrypt
    networks:
      default:
        ipv4_address: 10.10.10.100

  matrix-postgres:
    container_name: matrix-postgres
    image: snowinmars/matrix-postgres:1.0.0
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    # restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.10.10.2
    volumes:
      - ./postgres/postgresdata:/var/lib/postgresql/data
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=kljfdgkjbflkbjnlkdjfhg
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C

  matrix-synapse:
    container_name: matrix-synapse
    image: matrixdotorg/synapse:v1.77.0
    build:
      context: ./synapse
    depends_on:
      - matrix-postgres
    # restart: unless-stopped
    volumes:
      - ./synapse:/data
      - ./mautrix-telegram/registration.yaml:/data/brigres/telegram/registration.yaml
    networks:
      default:
        ipv4_address: 10.10.10.3

  matrix-element:
    container_name: matrix-element
    image: vectorim/element-web:v1.11.23
    build:
      context: ./element
    depends_on:
      - matrix-synapse
    # restart: unless-stopped
    volumes:
      - ./element/config.json:/app/config.json
    networks:
      default:
        ipv4_address: 10.10.10.4

  mautrix-telegram:
    image: dock.mau.dev/mautrix/telegram:v0.13.0
    container_name: mautrix-telegram
    build:
      context: ./mautrix-telegram
    depends_on:
      - matrix-element
    # restart: unless-stopped
    volumes:
      - ./mautrix-telegram:/data:z
    networks:
      default:
        ipv4_address: 10.10.10.10

networks:
  default:
    name: matrix_net